# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
        contents: read
        pull-requests: write
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        include:
        - language: c-cpp
          build-mode: manual
        - language: typescript
          build-mode: none
    steps:
    - uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: manual
    - uses: github/codeql-action/analyze@v3
      with:
          category: "/language:${{ matrix.language }}"
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.4.1'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run compile
    - run: npm run build
